### ISSUE TITLE
Pipeline to same cluster in different namespace

### ISSUE THREAD

**Issue by alexanderkogan** [dvallin/spacegun#70]
**Is your feature request related to a problem? Please describe.**
We are thinking about deploying the prelive and live pods in the same cluster separated by namespaces. This would currently not work with the pipeline, since it can only deploy into the same namespace in different clusters.

**Describe the solution you'd like**
The pipeline should support a definiton, where you can provide a cluster and a source and target namespace. Spacegun would then compare the deployments of these namespaces and update the target namespace to the deployment versions of the source namespace.

I guess the pipeline could look something like this:
```
cluster: <source (and target) cluster>
namespace: <source namespace> (optional)
start: "plan"
steps:
- name: "plan"
  type: "planDeployment"
  cluster: <target cluster>        | either one
  namespace: <target namespace>    |
...
```

**Describe alternatives you've considered**
- The step type could stay the same and allow only one of cluster or namespace.
- Alternatively you could add the type planNamespaceDeployment to have a strong differentiation.
- A target field with the members cluster and namespace would also be possible, but I think that's too much indentation.
